Repository kubegems/kubegems, pull requests merged in 2022-07, with the labels that each got.

#147 Prepare release v1.21.0
  CHANGELOG.md
  RELEASE.md
  VERSION
Labels: ignore-for-release

#152 🐞 fix(log): alert duration in template limit to 10m
  pkg/service/handlers/environment/handler.go
  pkg/utils/prometheus/log_alert.go
Labels: enhancement

#159 fix(plugin): #155 gpu can't regist device
  deploy/plugins/tke-gpu-manager/templates/tke-gpu-manager.yaml
Labels: bug

#161 🐞 fix(workload): workload list istio-inject sort error
  pkg/service/handlers/microservice/virtualspace.go
Labels: bug

#164 Correct grammar mistakes
  README.md
Labels: ignore-for-release

#166 🎈 perf(ingress): add ingressClass in plugin ingresses
  deploy/plugins/grafana/templates/grafana.yaml
  deploy/plugins/kubegems/templates/ingress.yaml
  deploy/plugins/monitoring/templates/kube-prometheus-stack.yaml
Labels: enhancement

#167 feat(gateway): gateway plugin use kubegems/ingress-nginx-operator to replace nginxinc/nginx-ingress-operator
  deploy/plugins/gateway/templates/gateway.yaml
  deploy/plugins/gateway/templates/metrics.yaml
  deploy/plugins/gateway/templates/nginxingresscontrollers.k8s.nginx.org.yaml
  deploy/plugins/kubegems-local/templates/controller/deployment.yaml
  go.mod
  go.sum
  pkg/apis/gems/common.go
  pkg/controller/controller.go
  pkg/controller/controllers/pluginstatus_controller.go
  pkg/controller/controllers/tenantgateway_controller.go
  pkg/controller/webhooks/handler.go
  pkg/controller/webhooks/m_tenantgateway.go
Labels: feature

#171 🐞 fix(webhook): ingress api version error
  deploy/plugins/kubegems-local/templates/controller/webhook-configuration.yaml
Labels: bug

#172 🐞 fix(cluster): apiserver version should from k8s, not db
  pkg/service/handlers/cluster/handler.go
  pkg/utils/agents/clientset.go
Labels: bug

#173 ✨ feat(gpu): add nvidia dcgm-exporter plugin
  deploy/plugins/dcgm-exporter/Chart.lock
  deploy/plugins/dcgm-exporter/Chart.yaml
  deploy/plugins/dcgm-exporter/plugin.yaml
  deploy/plugins/dcgm-exporter/templates/dcgm-exporter.yaml
  deploy/plugins/dcgm-exporter/values.yaml
Labels: feature

#175 🐞 fix(apiresource): handle apiresource group failed error
  pkg/agent/apis/cluster.go
Labels: bug
