Repository kubegems/kubegems, pull requests merged in 2022-09, with the labels that each got.

#219 feat(spm): upgrade jaeger and opentelmetry
  deploy/plugins/opentelemetry/Chart.yaml
  deploy/plugins/opentelemetry/templates/opentelemetry.yaml
  deploy/plugins/tracing/templates/observability.yaml
  deploy/plugins/tracing/values.yaml
Labels: feature

#228 fix(#222): nacos install default namespace
  deploy/plugins/nacos/Chart.yaml
  deploy/plugins/nacos/templates/nacos.yaml
Labels: bug

#225 ✨ feat(plugin): logging support aws loki storage
  deploy/plugins/logging/templates/loki.yaml
  deploy/plugins/logging/values.yaml
Labels: feature

#226 Merge release 1.21 to main
  go.mod
  go.sum
  pkg/agent/apis/rest.go
  pkg/agent/cluster/cluster.go
  pkg/service/handlers/cluster/handler.go
  pkg/service/handlers/sels/sels.go
  pkg/service/models/cache/model_cache.go
Labels: ignore-for-release

#233 🎈 perf(cluster): sync cluster version in worker
  pkg/worker/task/cluster_sync.go
  pkg/worker/task/tasks.go
Labels: enhancement

#242 🔧 build(generate): update release version in deploy yaml and docs
  Makefile
  README.md
  README_zh.md
  VERSION
  deploy/installer.yaml
  deploy/kubegems.yaml
  deploy/plugins/kubegems-installer/Chart.yaml
Labels: enhancement

#249 🎈 perf(monitor): container tpl use workload variable, rm uniqindex
  config/dashboards/container.yaml
  pkg/service/models/model_monitor_dashboard.go
Labels: enhancement

#251 🎈 perf(alert): do not check when delete promql tpl
  pkg/service/handlers/environment/handler.go
  pkg/service/handlers/observability/metrics.go
  pkg/service/handlers/observability/monitor.go
  pkg/utils/agents/extend.go
  pkg/utils/prometheus/monitor_alert.go
Labels: enhancement

#254 Bufix concurrent map
  pkg/service/handlers/observability/metrics.go
Labels: bug

#265 Merge log monitor receiver
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/agent/apis/cluster.go
  pkg/service/handlers/observability/log.go
  pkg/service/handlers/observability/monitor.go
  pkg/service/handlers/observability/receiver.go
  pkg/utils/agents/extend.go
  pkg/utils/prometheus/receiver.go
  pkg/utils/prometheus/receiver_test.go
  pkg/utils/prometheus/types.go
  scripts/generate-system-alert/main.go
  scripts/release-1.20.0-beta.2-update/main.go
  scripts/release-1.21-update/main.go
Labels: change

#269 docs: add contributors on readme
  README.md
  README_zh.md
Labels: documentation
