Repository kubegems/kubegems, pull requests merged in 2022-08, with the labels that each got.

#177 remove componentstatus api
  pkg/agent/apis/apis.go
  pkg/agent/apis/prometheus.go
Labels: change

#183 add gpu recording rule
  deploy/plugins/dcgm-exporter/templates/recording-rule.yaml
Labels: enhancement

#179 bugfix(id: 178): add thirdparty crd roles tracked by events
  deploy/plugins/argo-rollouts/templates/rollout-crd-view.yaml
  deploy/plugins/kubegems/templates/kuebgems-crd-view.yaml
  deploy/plugins/kubevela/templates/kubevela-crd-view.yaml
  deploy/plugins/logging/templates/logging-crd-view.yaml
  deploy/plugins/openkruise/templates/openkruise-crd-view.yaml
  deploy/plugins/volume-snapshoter/templates/external-snapshotter-crd-view.yaml
Labels: bug

#182 bugfix: imagePullSecrets error
  pkg/controller/controllers/environment_controller.go
  pkg/service/handlers/environment/handler.go
  pkg/service/handlers/registry/registry-hook.go
  pkg/service/handlers/registry/synchronizer/imageRegistrySynchronizer.go
  pkg/utils/set/set.go
  pkg/utils/set/set_test.go
  pkg/utils/slice/string.go
Labels: bug

#190 🐞 fix(jwt): fix empty jwt payload
  pkg/service/aaa/auth/middleware.go
  pkg/service/handlers/observability/base.go
Labels: bug

#193 Merge release 1.21
  CHANGELOG.md
  README.md
  VERSION
  deploy/plugins/kubegems-local/templates/controller/webhook-configuration.yaml
  pkg/agent/apis/cluster.go
  pkg/service/handlers/cluster/handler.go
  pkg/service/handlers/registry/synchronizer/imageRegistrySynchronizer.go
  pkg/utils/agents/clientset.go
Labels: ignore-for-release

#197 🐞 fix(prometheus): query should not unescape again
  pkg/agent/apis/prometheus.go
Labels: bug

#199 🎈 perf(metrics): add sumby when query from template
  pkg/service/handlers/observability/metrics.go
  pkg/utils/prometheus/promql/promql.go
Labels: enhancement

#205 🐞 fix(metrics): label query use full vectorselector expr
  pkg/service/handlers/observability/alert.go
  pkg/service/handlers/observability/metrics.go
  pkg/utils/prometheus/promql/promql.go
  pkg/utils/prometheus/promql/promql_test.go
Labels: bug

#206 ✨ feat(monitor): add monitor collector status api
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/agent/apis/apis.go
  pkg/agent/apis/prometheus.go
  pkg/service/handlers/observability/base.go
  pkg/service/handlers/observability/monitor.go
  pkg/utils/agents/extend.go
Labels: feature

#209 refactor promql tpl to support 3-level directory
  Dockerfile
  config/promql_tpl.yaml
  deploy/plugins/monitoring/templates/kubegems-default-monitor-amconfig.yaml
  deploy/plugins/monitoring/templates/kubegems-default-monitor-promrule.yaml
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/service/handlers/alerts/alerts.go
  pkg/service/handlers/environment/handler.go
  pkg/service/handlers/observability/alert.go
  pkg/service/handlers/observability/alerts_test.go
  pkg/service/handlers/observability/base.go
  pkg/service/handlers/observability/dashboard.go
  pkg/service/handlers/observability/log.go
  pkg/service/handlers/observability/metrics.go
  pkg/service/handlers/observability/monitor.go
  pkg/service/models/base.go
  pkg/service/models/model_promql_template.go
  pkg/utils/agents/extend.go
  pkg/utils/database/helper.go
  pkg/utils/gormdatatypes/json_slice.go
  pkg/utils/prometheus/alert.go
  pkg/utils/prometheus/config.go
  pkg/utils/prometheus/log_alert.go
  pkg/utils/prometheus/monitor_alert.go
  pkg/utils/prometheus/monitor_alert_test.go
  pkg/utils/prometheus/types_test.go
  scripts/generate-promql-tpl/main.go
  scripts/generate-promql-tpl/old.yaml
  scripts/generate-system-alert/main.go
  scripts/generate-system-alert/system-alert.yaml
Labels: change

#211 🎈 perf(cluster): return client cert expire time
  pkg/service/handlers/cluster/handler.go
  pkg/service/models/model_cluster.go
  pkg/utils/agents/client.go
Labels: enhancement

#210 feat(dashboard): manage dashboard templates, and import these when init mysql
  Dockerfile
  config/dashboards/consul.yaml
  config/dashboards/container.yaml
  config/dashboards/elasticsearch.yaml
  config/dashboards/kafka.yaml
  config/dashboards/mongodb.yaml
  config/dashboards/mysql.yaml
  config/dashboards/postgres.yaml
  config/dashboards/redis.yaml
  deploy/plugins/monitoring/templates/kubegems-default-monitor-promrule.yaml
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/service/handlers/alerts/alerts.go
  pkg/service/handlers/observability/base.go
  pkg/service/handlers/observability/dashboard.go
  pkg/service/handlers/observability/metrics.go
  pkg/service/models/base.go
  pkg/service/models/model_monitor_dashboard.go
  pkg/service/models/model_promql_template.go
  pkg/utils/database/helper.go
  pkg/utils/prometheus/monitor_alert.go
  pkg/utils/prometheus/templates/tpl.go
  scripts/generate-system-alert/main.go
Labels: feature

#212 ✨ feat(token): user token manage
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/service/handlers/oauthserver/oauth.go
  pkg/service/handlers/observability/dashboard.go
  pkg/service/models/base.go
  pkg/service/models/model_user.go
  pkg/service/routers/router.go
Labels: feature

#213 Bugfix image pull secerts error
  pkg/controller/controllers/environment_controller.go
  pkg/service/handlers/environment/handler.go
  pkg/service/handlers/registry/registry-hook.go
  pkg/service/handlers/registry/synchronizer/imageRegistrySynchronizer.go
  pkg/utils/set/set.go
  pkg/utils/set/set_test.go
  pkg/utils/slice/string.go
Labels: bug

#214 🐞 fix(eventer): drop 'lease' event
  deploy/plugins/eventer/templates/eventer.yaml
Labels: bug

#215 ✨ feat(announcement): add announcement api
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/service/handlers/announcement/announcement.go
  pkg/service/models/base.go
  pkg/service/models/model_announcement.go
  pkg/service/routers/router.go
Labels: feature

#216 Merge release 1.21.3
  deploy/plugins/eventer/templates/eventer.yaml
  scripts/release-1.21-update/README.md
  scripts/release-1.21-update/exec.sh
  scripts/release-1.21-update/main.go
Labels: ignore-for-release

#217 ✨ feat(dashboard): add variables
  config/dashboards/consul.yaml
  config/dashboards/container.yaml
  config/dashboards/elasticsearch.yaml
  config/dashboards/kafka.yaml
  config/dashboards/mongodb.yaml
  config/dashboards/mysql.yaml
  config/dashboards/postgres.yaml
  config/dashboards/redis.yaml
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/service/handlers/observability/metrics.go
  pkg/service/models/model_monitor_dashboard.go
  pkg/utils/gormdatatypes/json_map.go
Labels: feature
