Repository kubegems/kubegems, pull requests merged in 2022-10, with the labels that each got.

#282 ✨ feat(receiver): add alert proxy receiver for feishu
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/agent/apis/alert.go
  pkg/agent/apis/pod.go
  pkg/utils/prometheus/receiver.go
Labels: feature

#284 ✨ feat(monitor): monitor plugin add alertproxy component
  deploy/plugins/monitoring/files/alertproxy.yaml
  deploy/plugins/monitoring/templates/_helpers.tpl
  deploy/plugins/monitoring/templates/alertproxy.yaml
  deploy/plugins/monitoring/values.yaml
  pkg/utils/prometheus/receiver.go
Labels: feature

#297 🦄 refactor(alert): add alert channel in db, remove receiver
  deploy/plugins/kubegems-installer/README.md
  deploy/plugins/kubegems-installer/values.yaml
  deploy/plugins/kubegems-local/README.md
  deploy/plugins/kubegems/README.md
  deploy/plugins/kubegems/templates/_init.tpl
  deploy/plugins/kubegems/values.yaml
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  go.mod
  pkg/service/handlers/alerts/alerts.go
  pkg/service/handlers/environment/handler.go
  pkg/service/handlers/observability/base.go
  pkg/service/handlers/observability/channel.go
  pkg/service/handlers/observability/log.go
  pkg/service/handlers/observability/metrics.go
  pkg/service/handlers/observability/monitor.go
  pkg/service/handlers/observability/receiver.go
  pkg/service/models/base.go
  pkg/service/models/model_alert_channel.go
  pkg/service/models/model_alert_channel_test.go
  pkg/service/models/model_monitor_dashboard.go
  pkg/service/models/model_promql_template.go
  pkg/service/observe/alert.go
  pkg/service/observe/client.go
  pkg/service/observe/log_alert.go
  pkg/service/observe/log_alert_test.go
  pkg/service/observe/monitor_alert.go
  pkg/service/observe/monitor_alert_test.go
  pkg/service/observe/types.go
  pkg/utils/agents/extend.go
  pkg/utils/prometheus/alert.go
  pkg/utils/prometheus/channels/channel.go
  pkg/utils/prometheus/channels/email.go
  pkg/utils/prometheus/channels/feishu.go
  pkg/utils/prometheus/channels/webhook.go
  pkg/utils/prometheus/generator.go
  pkg/utils/prometheus/graph.go
  pkg/utils/prometheus/receiver.go
  pkg/utils/prometheus/receiver_test.go
  scripts/generate-system-alert/main.go
  scripts/release-1.20.0-beta.2-update/main.go
  scripts/release-1.21-update/main.go
  scripts/release-1.22-update/main.go
Labels: change

#298 feat(models): support for modelDeployment recreate
  deploy/plugins/kubegems-models/crds/models.kubegems.io_modeldeployments.yaml
  deploy/plugins/seldon/templates/seldon-core-operator.yaml
  pkg/apis/models/v1beta1/types.go
  pkg/model/deployment/modelseldon.go
Labels: feature

#299 Feat channel test api
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/msgbus/switcher/alert.go
  pkg/msgbus/switcher/switch.go
  pkg/service/handlers/observability/base.go
  pkg/service/handlers/observability/channel.go
  pkg/utils/prometheus/alert.go
  pkg/utils/prometheus/channels/channel.go
  pkg/utils/prometheus/channels/email.go
  pkg/utils/prometheus/channels/feishu.go
  pkg/utils/prometheus/channels/webhook.go
Labels: feature

#230 ✨ feat(alert): use kubegems email alert template
  deploy/plugins/monitoring/Chart.yaml
  deploy/plugins/monitoring/templates/kube-prometheus-stack.yaml
  deploy/plugins/monitoring/templates/kubegems-email-template.yaml
  pkg/utils/prometheus/channels/email.go
Labels: feature

#304 🎈 perf(monitot): upgrade alertproxy from v0.1.0 to v0.2.0
  deploy/plugins/monitoring/files/alertproxy.yaml
  deploy/plugins/monitoring/values.yaml
Labels: enhancement

#305 🦄 refactor(alert):alert overview use created_at rather than starts_at
  pkg/service/handlers/observability/alert.go
Labels: enhancement
